New navigation
Altinn/app-frontend-react pull request #2831
Opened 2024-12-18 14:31 UTC by bjosttveit

## Description

## Related Issue(s)

- closes #{issue number}

## Verification/QA

- Manual functionality testing
  - [ ] I have tested these changes manually
  - [ ] Creator of the original issue (or service owner) has been contacted for manual testing (or will be contacted when released in alpha)
  - [ ] No testing done/necessary
- Automated tests
  - [ ] Unit test(s) have been added/updated
  - [ ] Cypress E2E test(s) have been added/updated
  - [ ] No automatic tests are needed here (no functional changes/additions)
  - [ ] I want someone to help me make some tests
- UU/WCAG ([follow these guidelines](https://aksel.nav.no/god-praksis/artikler/utvikling?tema=universell-utforming) until we have our own)
  - [ ] I have tested with a screen reader/keyboard navigation/automated wcag validator
  - [ ] No testing done/necessary (no DOM/visual changes)
  - [ ] I want someone to help me perform accessibility testing
- User documentation @ [altinn-studio-docs](https://github.com/Altinn/altinn-studio-docs)
  - [ ] Has been added/updated
  
  - [ ] No functionality has been changed/added, so no documentation is needed
  - [ ] I will do that later/have created an issue
  
- Support in Altinn Studio
  - [ ] Issue(s) created for support in Studio
  
  - [ ] This change/feature does not require any changes to Altinn Studio
- Sprint board
  - [ ] The original issue (or this PR itself) has been added to the Team Apps project and to the current sprint board
  - [ ] I don't have permissions to do that, please help me out
- Labels
  - [ ] I have added a `kind/*` label to this PR for proper release notes grouping
  - [ ] I don't have permissions to add labels, please help me out

2024-12-18 14:32 UTC, bjosttveit commented
/publish

2024-12-20 10:50 UTC, bjosttveit commented
/publish

2025-01-03 07:19 UTC, SimenRokaas commented
@bjosttveit I noen skjemaer har vi logikk som dette for å vise/skjule navbar. Eksempelvis når vi oppdager at utfyller ikke er tjenestepliktig og derfor ikke skal fylle ut skjemaet. Finnes tilsvarende for ny navigasjon?
```
    "layout": [
      {
        "id": "navbar1",
        "type": "NavigationBar",
        "hidden": ["notEquals", ["dataModel", "HasPrefillDataFromPlis"], true]
      },
```

2025-01-03 07:33 UTC, bjosttveit commented
> Finnes tilsvarende for ny navigasjon?

Ikke per nå nei, men bra innspill

2025-01-03 07:49 UTC, SimenRokaas commented
@bjosttveit Ang `taskNavigation` - jeg ser av json-schema at hvert objekt må være av typen `NavigationReceipt` eller `NavigationTask`. I eksemplet er de to første av typen `NavigationTask`. Men vi har normalt bare én "task" i våre skjemaer, nemlig `Task_1`. Hvordan får vi da inn Bekreftelse-ikonet? Prøvde å finne koden bak eksempel-skjemaet ("navigation-test"), men det er vel ikke public kanskje?
```
  "uiSettings": {
    "taskNavigation": [
      {
        "name": "tasks.form",
        "taskId": "Task_1"
      },
      {
        "taskId": "Task_Confirm"
      },
      {
        "type": "receipt"
      }
    ]
  }
```

2025-01-03 07:57 UTC, bjosttveit commented
> I eksemplet er de to første av typen `NavigationTask`. Men vi har normalt bare én "task" i våre skjemaer, nemlig `Task_1`. Hvordan får vi da inn Bekreftelse-ikonet?

Ikonet kommer an på task typen. Så bekreftelses-ikonet vises for confirmation tasker.

> Prøvde å finne koden bak eksempel-skjemaet ("navigation-test"), men det er vel ikke public kanskje?

Det skal være public, men det ligger på `dev.altinn.studio` så man må kanskje lage en egen bruker for å komme inn i der.

2025-01-03 08:15 UTC, SimenRokaas commented
> Ikonet kommer an på task typen. Så bekreftelses-ikonet vises for confirmation tasker.

Er "confirmation task" noe nytt? Ser ikke noe slikt i `process.bpmn` for [INT-1017](https://altinn.studio/repos/dsb/int-1017-personopplysninger/src/branch/master/App/config/process/process.bpmn) iallfall. Alle våre skjemaer har tilsvarende prosess-fil.

2025-01-03 08:21 UTC, SimenRokaas commented
Hadde det gått an å "fryse" side-navigasjonen når man skroller, slik at den alltid vises selv for litt lange skjemasider?

https://github.com/user-attachments/assets/2b9165fb-2ede-446f-bc24-7ba6528c0085

2025-01-03 08:23 UTC, bjosttveit commented
> Er "confirmation task" noe nytt? Ser ikke noe slikt i process.bpmn for [INT-1017](https://altinn.studio/repos/dsb/int-1017-personopplysninger/src/branch/master/App/config/process/process.bpmn) iallfall. Alle våre skjemaer har tilsvarende prosess-fil.
>
> EDIT: Stryk siste. Vi droppet nok bekreft-task ganske tidlig for alle våre skjemaer, fordi vi fant ut at det holder med sammendrag + kvittering.

Confirmation task er et litt gammelt konsept og jeg har inntrykk av at de fleste kommer til samme konklusjon om at det ikke gir noen særlig verdi fremfor å ha oppsummeringssider i skjemaet. Jeg tok det med i eksempel-appen for å vise hvordan navigasjonen viser andre steg med forskjellig type. Dersom man for eksempel bruker signering får man noe tilsvarende, men med et annet ikon.

2025-01-03 08:26 UTC, bjosttveit commented
> Hadde det gått an å "fryse" side-navigasjonen når man skroller, slik at den alltid vises selv for litt lange skjemasider?

Vi diskuterte det ganske tidlig, men problemet er hvordan det oppfører seg hvis navigasjonen blir litt for lang eller skjermen litt for kort til å få plass til hele navigasjonen i høyden. Da måtte den hatt sin egen scroll-bar og det er fort mer rotete å forholde seg til

2025-01-03 08:41 UTC, SimenRokaas commented
Hva er det som styrer om en side for "avhuket"-ikon? Her har vi en side der ingenting er påkrevd, det er altså OK å bare gå videre. Da får ikke siden noe avhuket-ikon, og det ser antagelig litt snålt ut for bruker.

https://github.com/user-attachments/assets/53a27f8b-5610-404c-b980-e065d2647080

2025-01-03 08:59 UTC, SimenRokaas commented
Etterhvert vil vi trenge tilbakemelding fra fagavdeling på ny navigering. Når kan funksjonaliteten bli tilgjengelig for deploy til  TT02?

2025-01-03 09:03 UTC, bjosttveit commented
> Hva er det som styrer om en side får "avhuket"-ikon? Her har vi en side der ingenting er påkrevd, det er altså OK å bare gå videre. Da får ikke siden noe avhuket-ikon, og det ser antagelig litt snålt ut for bruker.

Det som gir avhuket ikon er at man ikke har noen valideringsfeil på siden. Vi har ingen annen god måte (såvidt meg bekjent) å definere at alt er "ferdig utfylt" i det generelle caset, det er jo TE som eier datamodellen og layout. En konsekvens av det er at sider som ikke har noe som er påkrevd å fylle ut enten fordi ingenting har `required` eller at siden kun inneholder informasjons-tekst og ingen utfyllingskomponenter, ville blitt markert som "ferdig" før brukeren i det hele tatt har sett innholdet. Derfor er det en tilleggsbetingelse at siden må inneholde mist ett påkrevd felt for at den skal kunne bli markert som "ferdig", og hvis ikke så holder den seg nøytral. Akkurat dette er veldig vanskelig for oss å komme med en definisjon som fungerer for alle mulige caser, men dette er foreløpig det beste vi har fått til.

I den casen du har på videoen er jeg enig i at det kan være litt forvirrende, når alle de andre sidene markeres som ferdig bortsett fra den, og den siden ser ut som en helt vanlig utfyllingsside. Men problemet for oss er når skulle vi markert den som ferdig?

I vår testapp har vi de to info-sidene i starten av skjemaet som heller ikke har noe påkrevd, og hvis de var markert som ferdig ville det også vært forvirrende 😅

2025-01-03 09:04 UTC, bjosttveit commented
> Når kan funksjonaliteten bli tilgjengelig for deploy til TT02?

Det er ikke noe i veien for å deploye med preview versjon til tt02, bare hold det unna prod 😅

2025-01-03 12:02 UTC, bjosttveit commented
/publish

2025-01-07 14:09 UTC, SimenRokaas commented
Kvittering: Denne vises alltid deaktivert - mens på selve kvitteringssiden forsvinner hele navigasjonsstrukturen. Er det tenkt at strukturen skal vises, da med "resten" deaktivert?

2025-01-07 14:14 UTC, SimenRokaas commented
Tester har kommentert en del på grupperings-ikonene. Siden de er klikkbare har tester blandet dem sammen med side-ikonene, og kommenterert ting som at gruppe- og side-ikon viser samme side, og at man ikke trenger to ikoner for det samme. Gjelder da intro-siden som bare har en side i gruppen.

Må alle sider være i en gruppe? Vi har jo ikke hatt denne oppdelingen så langt, og ser nå at det blir litt UX-utfordring ved at alle sider må inn i en gruppe.

2025-01-08 08:29 UTC, bjosttveit commented
>     Ved prefill blir mange av sidene markert som "ferdig" eller "feil" uten at bruker har vært innom siden.

Jeg var redd for det ja, men spesielt "ferdig". Hvis en side markeres som "feil" uten at bruker har vært innom er vel også den feil-oppsummeringen synlig på bunn av siden?

2025-01-08 09:16 UTC, bjosttveit commented
> Kvittering: Denne vises alltid deaktivert - mens på selve kvitteringssiden forsvinner hele navigasjonsstrukturen. Er det tenkt at strukturen skal vises, da med "resten" deaktivert?

Vi hadde det til å begynne med, men nå viser vi ikke navigasjon på kvitteringssiden i det hele tatt. Hvordan synes du det bør oppføre seg?

2025-01-08 09:17 UTC, Edavda commented
> Kvittering: Denne vises alltid deaktivert - mens på selve kvitteringssiden forsvinner hele navigasjonsstrukturen. Er det tenkt at strukturen skal vises, da med "resten" deaktivert?

Tanken her var å vise kvitteringssiden i navigasjonen for å tydeliggjøre det siste steget i skjemaet. Men den vil alltid være deaktivert fram til man faktisk er på kvitteringssiden. Og når man er på kvitteringssiden, så har vi svært begrenset med informasjon om det tidligere utfyllingssteget. 

Det vil si at vi ikke kan vise navigasjonen på samme måte som man så den under utfylling, men kun vise hva de tidligere stegene var. Derfor valgte vi å fjerne visningen av navigasjonen på kvitteringssiden.

2025-01-08 10:49 UTC, SimenRokaas commented
> > Kvittering: Denne vises alltid deaktivert - mens på selve kvitteringssiden forsvinner hele navigasjonsstrukturen. Er det tenkt at strukturen skal vises, da med "resten" deaktivert?
> 
> Vi hadde det til å begynne med, men nå viser vi ikke navigasjon på kvitteringssiden i det hele tatt. Hvordan synes du det bør oppføre seg?

Hvis det ikke er mulig å vise strukturen på samme måte i kvitteringssiden (men med alle foregående steg deaktivert) - og Edvins svar tyder jo på det - så foretrekker vi å ikke vise kvittering-ikonet i det hele tatt.

2025-01-08 11:10 UTC, bjosttveit commented
> Hvis det ikke er mulig å vise strukturen på samme måte i kvitteringssiden (men med alle foregående steg deaktivert) - og Edvins svar tyder jo på det - så foretrekker vi å ikke vise kvittering-ikonet i det hele tatt.

Åja, jeg kan forklare litt:
Vi kan vise navigasjonen i kvittering. Men, vi kjører ikke expressions for tidligere steg, så vi kan ikke vite nøyaktig hvilke sider som ble vist i forrige steg, og dermed kan vi ikke nødvendigvis vise de faktiske gruppene og sidene som var på det steget når man står i kvitteringen. Det vi kan vise er selve prosess-steget (da som én enkelt boks som er deaktivert). Og det er det vi gjør når man har satt opp `taskNavigation` i layout-sets. I tillegg ville det jo i mange tilfeller vært ganske støyete å vist alle gruppene på alle tidligere steg om man f.eks. har flere utfyllingssteg.

Det er valgfritt å vise kvittering (kan fjernes fra `taskNavigation`)

2025-01-08 11:47 UTC, SimenRokaas commented
> Det er valgfritt å vise kvittering (kan fjernes fra `taskNavigation`)

Ja, det er det vi har gjort nå. Skulle sagt det, beklager.

2025-01-08 11:50 UTC, SimenRokaas commented
> > Ved prefill blir mange av sidene markert som "ferdig" eller "feil" uten at bruker har vært innom siden.
> 
> Jeg var redd for det ja, men spesielt "ferdig". Hvis en side markeres som "feil" uten at bruker har vært innom er vel også den feil-oppsummeringen synlig på bunn av siden?

Hmm, jeg var litt for kjapp der. Testet litt nå, og når prefill kommer med data som ikke valideres så vises ikke feil for den siden før man faktisk går til den siden og trigger validering der. Virker rart - siden de andre sidene er markert "ferdig" så er det vel kjørt validering der?
En liten filmsnutt for å illustrere:

https://github.com/user-attachments/assets/3fb2edda-8e6b-4865-8552-952170bb9912

2025-01-08 12:09 UTC, bjosttveit commented
> Testet litt nå, og når prefill kommer med data som ikke validerer så vises ikke feil for den siden før man faktisk går til den siden og trigger validering der. Virker rart - siden de andre sidene er markert "ferdig" så er det vel kjørt validering der?

Det var en veldig bra case. Vi kjører validering hele tiden, så vi vet alltid hva tilstanden er, men vi har et system for å begrense synligheten av validerings-feil sånn at det ikke skal bli for masete. For å sjekke om noe er "ferdig" så sjekker vi validerings-staten uavhengig av om feilene er synlig eller ikke sånn at en side ikke først kan markeres som "ferdig", men deretter vise validerings-feil når man trykker på neste uten å endre noe på siden.

Så det er derfor den siden i videoen ikke markeres som "ferdig" selv om alt er fylt ut, fordi det er validerings-feil på siden (som ikke er synlig enda).

Dette er forsåvidt en case jeg visste kom til å være problematisk med hvordan "ferdig"-logikken fungerer, siden alt er egentlig fylt ut fra før, men du vil vel at brukeren skal se over informasjonen? Så det er vel egentlig bare dumt å markere noe som "ferdig" for det er mer opp til om brukeren har tatt stilling til det som er preutfylt eller ikke?

Hvordan ville du at oppførselen skulle vært i den casen der? Ville du ikke hatt noen "ferdig"-markering fordi brukeren ikke egentlig skal fylle ut noe nytt? Eller ville du hatt det, men at det oppførte seg på en annen måte enn i dag?

2025-01-09 13:41 UTC, bjosttveit commented
/publish

2025-01-09 14:34 UTC, SimenRokaas commented
Hva betyr 👍  på kommentarene mine fra tirsdag 7/1? Kunne dere svart ut hvert enkelt punkt?

2025-01-09 14:56 UTC, Edavda commented
@SimenRokaas Tror folk bruker 👍 litt forskjellig, så det er bra du ber om et ordentlig svar :) 

> Tester har kommentert en del på grupperings-ikonene. Siden de er klikkbare har tester blandet dem sammen med side-ikonene, og kommenterert ting som at gruppe- og side-ikon viser samme side, og at man ikke trenger to ikoner for det samme. Gjelder da intro-siden som bare har en side i gruppen.
> 
> Må alle sider være i en gruppe? Vi har jo ikke hatt denne oppdelingen så langt, og ser nå at det blir litt UX-utfordring ved at alle sider må inn i en gruppe.

Kan du utdype litt om hvordan de blandet sammen ikonene? 
Vil det si at de forventet å komme direkte til en side når de trykket på gruppe-ikonet? 

> Kan gruppering gjøres valgfritt? Da kan man ha en landingsside (introduksjon) som ikke er noen gruppe først, deretter ufyllingssider i en gruppe - eller ikke, hvis det bare er én utfyllingsside.

Dette er noe vi må undersøke litt videre og vi ønsker gjerne litt mer tilbakemeldinger fra fler før vi bestemmer oss for en retning. Vi ser at det kan være litt tungvint å kunn ha en side i en gruppe, men samtidig så er vi usikre på hvordan det vil oppfattes å blande grupper og fristilte sider. 

> Viktigst: Det hadde vært fint om det fantes en mulighet for (ved konfigurasjon) at alle sidene kunne vises hele tiden. Det er forvirrende/irriterende for tester at de hele tiden kollapses når man går til en side i en annen gruppe. Dette kom også fram ved innsending med valideringsfeil - da vises feilikon for gruppa mens sidene er kollapset.

Det er notert - vi skal undersøke 👍 
Hvordan foregår testingen forresten? 

> Kan grupperings-tekstene vises i Fet skrift? Det gjør det lettere å skille dem fra sidene.

Vi har unngått dette så langt ettersom fonten som brukes kun har vanlig tykkelse og veldig fet type. Jeg er enig i at gruppe-titlene kan tydeliggjøres mer, men samtidig så blir det veldig tungt med så mye fet skrift på siden av skjema. Vi har planer om å jobbe videre med font og typografi fremover og det vil gi oss flere muligheter med å justere hvor fet skriften kan være. Så vi ønsker å avvente litt med å gjøre en slik endring enn så lenge.

2025-01-10 07:55 UTC, SimenRokaas commented
> Kan du utdype litt om hvordan de blandet sammen ikonene? Vil det si at de forventet å komme direkte til en side når de trykket på gruppe-ikonet?

Ja, stemmer. Siden gruppe-begrepet er helt nytt og brukerne er vant til at klikkbare elementer i nåværende navbar tar dem til en side så er det kanskje ikke så rart. Ikonene og tekstene for grupper og sider er jo også såpass like i størrelse og utforming at det nok bidrar til misforståelsen.

> > Kan gruppering gjøres valgfritt? Da kan man ha en landingsside (introduksjon) som ikke er noen gruppe først, deretter ufyllingssider i en gruppe - eller ikke, hvis det bare er én utfyllingsside.

> Dette er noe vi må undersøke litt videre og vi ønsker gjerne litt mer tilbakemeldinger fra fler før vi bestemmer oss for en retning. Vi ser at det kan være litt tungvint å kunn ha en side i en gruppe, men samtidig så er vi usikre på hvordan det vil oppfattes å blande grupper og fristilte sider.

Skjønner det. Men det burde være mulig å kun vise sider. Vi ønsker jo å ta i bruk ny struktur, og da ønsker vi å gjøre det for alle skjemaene våre for å ha gjenkjennbarhet, lik kode etc. Men mange av skjemaene våre er små (kun innledning + en utfyllingsside) og der blir det kunstig å ha en gruppe for hver side.

> > Viktigst: Det hadde vært fint om det fantes en mulighet for (ved konfigurasjon) at alle sidene kunne vises hele tiden. Det er forvirrende/irriterende for tester at de hele tiden kollapses når man går til en side i en annen gruppe. Dette kom også fram ved innsending med valideringsfeil - da vises feilikon for gruppa mens sidene er kollapset.
> 
> Det er notert - vi skal undersøke 👍 Hvordan foregår testingen forresten?

Testingen foregår stort sett ved at tester initierer skjema direkte i TT02. Noen få skjemaer har prefill-data som er skrivebeskyttet for utfyller, de testes ved at de initieres fra våre systemer med prefill-data vha API-kall.

2025-01-10 07:59 UTC, SimenRokaas commented
> > Hvordan ville du at oppførselen skulle vært i den casen der? Ville du ikke hatt noen "ferdig"-markering fordi brukeren ikke egentlig skal fylle ut noe nytt? Eller ville du hatt det, men at det oppførte seg på en annen måte enn i dag?
> 
> Tilbakemeldingen fra Sivilforsvaret er at det mest logiske hadde vært at markering av "ferdig" (eller "feil") for en side settes når bruker klikker Neste.

Har dere fått sett noe på dette? Dette er veldig viktig for oss. Uten dette blir det vanskelig for oss å ta i bruk ny struktur, fordi den vil virke mot sin hensikt for skjemaene som har prefill der vi ønsker at utfyller sjekker og endrer/retter opplysningene vi har på dem.

2025-01-10 08:05 UTC, SimenRokaas commented
> Skjønner det. Men det burde være mulig å kun vise sider. Vi ønsker jo å ta i bruk ny struktur, og da ønsker vi å gjøre det for alle skjemaene våre for å ha gjenkjennbarhet, lik kode etc. Men mange av skjemaene våre er små (kun innledning + en utfyllingsside) og der blir det kunstig å ha en gruppe for hver side.

Eksempel på et slikt enkelt skjema:
![image](https://github.com/user-attachments/assets/f8177a97-1df6-4e2c-afa1-f1fe52d054dc)

2025-01-10 08:52 UTC, bjosttveit commented
> Har dere fått sett noe på dette? Dette er veldig viktig for oss. Uten dette blir det vanskelig for oss å ta i bruk ny struktur, fordi den vil virke mot sin hensikt for skjemaene som har prefill der vi ønsker at utfyller sjekker og endrer/retter opplysningene vi har på dem.

Dette krever litt mer diskusjon hos oss, så det er veldig bra at vi har fått noen reelle caser fra dere vi kan ta med oss der. Jeg tenker at vi må gjøre noe med dette før vi releaser, enten fjerne markeringen i første omgang eller gjøre det mulig å skru det av. Og så skal vi prøve å få oppførselen til å bli bedre. 

Men det er veldig vanskelig å få "ferdig"-markering til å fungere bra i absolutt alle caser ut av boksen, så jeg tenker vi må ha litt mulighet for manuell overstyring der det ikke egner seg.

> Tilbakemeldingen fra Sivilforsvaret er at det mest logiske hadde vært at markering av "ferdig" (eller "feil") for en side settes når bruker klikker Neste.

Jeg er litt skeptisk til et sånt mønster, det åpner i hvert fall en del nye problemer: 
Hva skjer hvis man hopper tilbake til en tidligere side da? Er ikke siden markert som "ferdig" lenger? Hvis den gjør det, hva skjer om man refresher siden? Skal vi lagre hvilke sider brukeren har vært innom? Jeg tror det vil skape forvirring bare på andre måter enn nå, så hvis det er slik at brukeren bare skal se over å rette opp informasjon men ikke fylle ut noe nytt så tenker jeg det bare er dumt å si noe om når ting er ferdig og ville tenkt at nøytralitet var bedre.

2025-01-10 14:38 UTC, SimenRokaas commented
> Jeg er litt skeptisk til et sånt mønster, det åpner i hvert fall en del nye problemer: 

Ser den. Hvis det blir mulig å "slå av" markering av "ferdig" per skjema, så tror jeg mye er løst. Da kan det slås av for slike "se gjennom opplysningene og rett eventuelle feil og mangler"-type skjemaer som SIV-1002 er et eksempel på. Markering av valideringsfeil derimot er det vel greit å alltid ha "påslått".

2025-01-10 14:59 UTC, bjosttveit commented
> Hvis det blir mulig å "slå av" markering av "ferdig" per skjema, så tror jeg mye er løst.

Ja jeg tenker vi kan tilby mulighet for å skru det av på skjema-, gruppe-, og side-nivå potensielt.

> Markering av valideringsfeil derimot er det vel greit å alltid ha "påslått".

Jeg tenker i alle fall det, det kommer bare i tillegg til den store røde boksen nederst, og er sånn sett mye mindre overveldene enn den er

2025-01-16 13:46 UTC, bjosttveit commented
/publish

2025-01-16 14:13 UTC, bjosttveit commented
/publish

2025-01-21 07:56 UTC, martinothamar commented
/publish

2025-01-21 08:13 UTC, martinothamar commented
/publish

2025-02-06 07:53 UTC, bjosttveit commented
/publish

2025-02-06 09:02 UTC, bjosttveit commented
@SimenRokaas angående problemene du rapportere om "ferdig" markering. Den ene hvor en side ikke markeres selv om alle rundt markeres, og den der sider med prefill markeres uten at brukeren har vært innom. Nå har jeg endret slik at vi ser på hvilke sider brukeren har vært innom (ved bruk av neste-knapper, man kan fortsatt hoppe fritt i navigasjons-menyen uten å endre tilstanden) i tillegg til sjekk på at validering er OK. Fortsatt usikker på når vi eventuelt skal si at "brukeren har vært innom", men tror dette vil fungere bedre. Dette er også gjort om til en opt-in egenskap på gruppe-nivå.

Angående "valgfri" gruppering, så er det nå mulig å ha "frittstående sider". Dvs. man må definere en gruppe, men hvis den bare har en side kan man sette `"single": true` så kan den ikke ekspanderes.

Er eksempler i test-appen og konfig-eksempler i beskrivelsen

2025-02-06 12:59 UTC, bjosttveit commented
/publish

2025-02-10 08:56 UTC, bjosttveit commented
/publish

2025-02-14 15:34 UTC, bjosttveit commented on src/features/navigation/PopoverNavigation.tsx
> +function usePageGroupProgress(): NavigationButtonData | null {
This is not used anymore, remove this

2025-02-14 15:36 UTC, bjosttveit commented on src/features/navigation/utils.ts
> + * 4. A group is marked as completed if any of its pages have no nodes with any validations errors (visible or not), and all of the pages are marked as 'visited'.
Consider updating this

2025-02-14 15:38 UTC, bjosttveit commented on src/hooks/useLocalStorageState.ts
> +class LocalStorageController<T> {
Resolve this

2025-02-17 07:28 UTC, bjosttveit commented
/publish

2025-02-18 10:10 UTC, olemartinorg approved these changes
Looks great!!

2025-02-18 13:41 UTC, bjosttveit commented on src/features/language/LanguageProvider.tsx
> +  const current =
Is it really breaking? Or was it a bug that we mixed languages previously? There are three different sources:
1. Language selector: it is not possible to select a language not supported by the app already, and it would previously show blank if an invalid language was selected to begin with.
2. From url: I guess this is mostly used by Service Owners when linking to their apps from their own sites. In this case I guess we could log a warning if the language you get in the url is not available.
3. Profile preferences: I think its correct to just ignore this if the app does not support it, no need to log a warning?

2025-02-18 13:43 UTC, bjosttveit commented on src/hooks/useLocalStorageState.ts
> +     * The native 'storage' event only gets called when localstorage is modified from a different browser context (e.g. a different tab),
I did this originally, but I was unsure if this would feel buggy wrt. the visited pages logic and how this impacts marking pages as completed 🤔

2025-02-18 13:48 UTC, bjosttveit commented on src/hooks/useLocalStorageState.ts
> +  let fullKey = `${window.org}/${window.app}`;
I wanted at least apps to be "isolated" by default, but for other things I'm not sure it is needed. For language we actively choose to isolate per user, but for visited pages I only care about instance/task etc. We don't have many use cases for localstorage currently so I don't know what the most sensible default is

2025-02-18 13:54 UTC, olemartinorg commented on src/features/language/LanguageProvider.tsx
> +  const current =
I think it's a bit of both. It's a common pattern to have partial translation support (i.e. show me everything you can in norwegian, but fall back to english when there is no norwegian translation). That matters for us as well, when we used to allow (indirect) selection of a language the app does not support (but our built-in texts do support). Since we have multiple sources (text-resources in apps, our built-in texts in app-frontend), we have a case similar to that.

So regardless of how we work around unsupported languages (**before:** _fail, partial translations_, **after:** _fall back to a supported language_) it's a good time to also inform app developers about why the language is the way it is. Especially when the behavior changes slightly. The multiple ways you can select a language (and it could break in the app before this fix) is also a good reason to inform the app developers about what we found out and why we ignored the setting. Without such a warning it is very difficult to figure out why the language doesn't 'stick'.

2025-02-18 13:55 UTC, olemartinorg commented on src/hooks/useLocalStorageState.ts
> +     * The native 'storage' event only gets called when localstorage is modified from a different browser context (e.g. a different tab),
Yep, that might be strange. Opening the same instance in two tabs will absolutely lead to strangeness, though! :face_with_peeking_eye:

2025-02-18 15:09 UTC, bjosttveit commented on src/hooks/useLocalStorageState.ts
> +     * The native 'storage' event only gets called when localstorage is modified from a different browser context (e.g. a different tab),
True, and it was fun having the app in two different tabs and changing the language for both in one go 😆

2025-02-19 09:04 UTC, olemartinorg commented on src/hooks/useLocalStorageState.ts
> +     * The native 'storage' event only gets called when localstorage is modified from a different browser context (e.g. a different tab),
Haha, oof, I agree - best to avoid stuff like this for a nice-to-have feature! :raised_hands:

2025-02-19 12:49 UTC, cammiida requested changes
Ikke helt ferdig, men skal prøve å skynde meg 😄

2025-02-19 13:29 UTC, bjosttveit commented on src/components/altinnAppHeader.tsx
Det er disse to, enig i at navnene er dritforvirrende, så kan godt rename ja

<img width="809" alt="bilde" src="https://github.com/user-attachments/assets/1859baea-51cc-42e0-8038-ab47668d7435" />

<img width="809" alt="bilde" src="https://github.com/user-attachments/assets/04aedbd1-c448-4dd9-85e8-e487fb3166ef" />

2025-02-19 13:38 UTC, bjosttveit commented on src/components/presentation/BackNavigationButton.tsx
> +  const queryParameterReturnUrl = new URLSearchParams(window.location.search).get('returnUrl');
Siden vi bruker hashrouter så blir ikke det det samme. Her er jeg ute etter queryParam som settes før hash-delen

2025-02-19 16:19 UTC, bjosttveit commented on src/components/presentation/BackNavigationButton.tsx
> +  const queryParameterReturnUrl = new URLSearchParams(window.location.search).get('returnUrl');
I dette tilfellet er det heller ikke noe reelt problem, så istedenfor å prøve å gjøre den reaktiv så skrev jeg en kommentar som forklarer saken sånn at man forstår hva som skal skje til senere

2025-02-19 16:27 UTC, bjosttveit commented on src/components/AltinnAppHeader.module.css
> +  margin-bottom: -6px;
Jo egentlig, vi bør kanskje rydde litt opp i de gamle greiene her, jeg gjorde bare litt mindre tweaks på den 🤔

2025-02-19 19:36 UTC, cammiida reviewed
Ferdig! Dette var et godt stykke arbeid 💪 💯 har noen kommentarer, men det skulle bare mangle når det er en såpass stor PR 😛

2025-02-20 07:38 UTC, bjosttveit commented on test/e2e/support/custom.ts
> +      cy.findByTestId('page-navigation-trigger').click();
Ja jeg følger stort sett den, men i dette tilfellet ville jeg gjerne lage metoder som fungerer uavhengig av om man er på desktop, tablet eller mobil sånn at jeg kunne skrive én test som kan kjøre på alle tre. Men det krever at jeg sjekker litt greier på forhånd for å vite om den må åpne menyen osv.

2025-02-20 07:40 UTC, bjosttveit commented on src/components/presentation/Header.tsx
> +            style={!aboveHeader ? { marginTop: 24 } : undefined}
Ja kan sikkert gjøre det litt annerledes. Det er egentlig bare for å forhindre layout-shift imens ting loader

2025-02-20 07:42 UTC, bjosttveit commented on src/core/contexts/processingContext.tsx
Grunnen til at jeg laget contexten var for å slippe å propdrille som jeg måtte gjort for å brukt hooken direkte. Har ikke tenkt på å bruke useMutation, kanskje jeg ikke trenger å finne opp hjulet på nytt? 🤔

2025-02-20 07:44 UTC, bjosttveit commented on src/features/form/layoutSets/LayoutSetsProvider.tsx
> +            taskNavigation: layoutSets.uiSettings.taskNavigation.map((g) => ({ ...g, id: uuidv4() })),
Jeg opplever ikke det som en konvensjon, har i alle fall ikke lagt spesielt merke til det noen steder 🤔

2025-02-20 07:55 UTC, bjosttveit commented on src/features/language/LanguageProvider.tsx
> +  const params = new URLSearchParams(window.location.hash.split('?')[1]);
I utgangspunktet ikke, fordi LanguageProvider er før RouterProvider 😕

2025-02-20 08:01 UTC, bjosttveit commented on src/features/instance/ProcessContext.tsx
> +export function useGetAltinnTaskType() {
`useTaskTypeFromBackend` henter tasktypen til current-task, men jeg trenger en funksjon som kan gi meg tasktypen til hvilken som helst task. Det brukes til å vise forskjellige ikoner for alle taskene i navigasjonen

2025-02-20 08:06 UTC, bjosttveit commented on src/utils/party.ts
> +export function renderPartyName(party?: IParty, userParty?: IParty) {
Det synes jeg også var litt forvirrende, men det er teknisk sett korrekt. Party er currentParty som du representerer, og userParty er fra profilen til den brukeren du er logget inn som (`user.party`), og det er jo faktisk en `IParty` det også. Har du forslag til et annet navn?

2025-02-20 08:12 UTC, bjosttveit commented on src/features/navigation/utils.ts
> +  const isCompleted = useMemo(() => {
Kan godt hende det ikke trengs, men i dette tilfelle siden den må iterere over alle nodene å hente valideringer osv. som også innebærer litt allokkering, så tviler jeg på at å sjekke de dependenciene faktisk er dyrere. Men dette har blitt litt vanesak for meg i alle fall når jeg bruker selectorer, siden jeg vet at de ikke oppdateres unødvendig ofte, men man hadde sikkert ikke merket noen forskjell

2025-02-20 12:24 UTC, bjosttveit commented on src/components/presentation/BackNavigationButton.tsx
> +    <Button
I eksempelet til design-systemet bruker de `a` istedenfor `Link`, fargen på teksten og text-decoration virker som kommer fra `Link` sin css, det funker uten å overstyre noe styling med å bruke `a` istedenfor. Så dere hadde lagt på en klasse for å fikse det

https://storybook.designsystemet.no/?path=/docs/komponenter-button--docs#knapp-som-lenke

2025-02-20 12:26 UTC, bjosttveit commented on src/components/presentation/BackNavigationButton.tsx
> +    <Button
Virker som isLoading fortsatt knekker den ganske greit med asChild, jeg gjorde samme endring som du lenket til

2025-02-20 12:44 UTC, bjosttveit commented on src/components/presentation/BackNavigationButton.tsx
> +    <Button
Men det gir uansett ikke mening å bruke sammen i guess

2025-02-20 13:54 UTC, cammiida commented on test/e2e/support/custom.ts
> +      cy.findByTestId('page-navigation-trigger').click();
Skjønner. Men jeg ville kanskje tenkt at det er bedre å skrive hver test for seg? Så blir det lettere å skjønne hva som skjer når (definitivt når) man må endre på testen + at man får testet nærmere det brukeren faktisk ser/blir lest opp.

2025-02-20 13:55 UTC, cammiida commented on src/core/contexts/processingContext.tsx
Forhåpentligvis 🤩 🙏

2025-02-20 13:55 UTC, cammiida commented on src/features/form/layoutSets/LayoutSetsProvider.tsx
> +            taskNavigation: layoutSets.uiSettings.taskNavigation.map((g) => ({ ...g, id: uuidv4() })),
Hm, kan godt være bare meg som har det fra kotlin-verden 😅

2025-02-20 14:03 UTC, cammiida commented on src/features/language/LanguageProvider.tsx
> +  const params = new URLSearchParams(window.location.hash.split('?')[1]);
Burde den være det? Er det noe i veien for å bare:
`index.tsx`
```tsx
const router = createHashRouter([
  {
    path: '*',
    element: (
      <LanguageProvider>
        <LangToolsStoreProvider>
          <ViewportWrapper>
            <UiConfigProvider>
              <AppRoutingProvider>
                <ErrorBoundary>
                  <Root />
                </ErrorBoundary>
              </AppRoutingProvider>
            </UiConfigProvider>
          </ViewportWrapper>
        </LangToolsStoreProvider>
      </LanguageProvider>
    ),
  },
]);

document.addEventListener('DOMContentLoaded', () => {
  propagateTraceWhenPdf();

  const container = document.getElementById('root');
  const root = container && createRoot(container);
  root?.render(
    <AppQueriesProvider {...queries}>
      <ErrorBoundary>
        <AppPrefetcher />
        <AppWrapper>
          <RouterProvider router={router} />
        </AppWrapper>
      </ErrorBoundary>
    </AppQueriesProvider>,
  );
});
```

2025-02-20 14:28 UTC, cammiida commented on src/features/navigation/utils.ts
> +  const isCompleted = useMemo(() => {
Vil argumentere, som det står i artikkelen, at sjansen for at det gjør ytelsen verre i tillegg til at det er vanskeligere å lese gjør at det ikke er verdt det. I hvert fall før man faktisk merker at man må ta grep. Og at det er veldig mange andre ting som man heller burde fokusere på når det kommer til ytelse. 

Fra artikkelen:
>MOST OF THE TIME YOU SHOULD NOT BOTHER OPTIMIZING UNNECESSARY RERENDERS. React is VERY fast and there are so many things I can think of for you to do with your time that would be better than optimizing things like this. In fact, the need to optimize stuff with what I'm about to show you is so rare that I've literally never needed to do it in the 3 years I worked on PayPal products and the even longer time that I've been working with React.

Og Mr. Dodds er veldig verdt å høre på 🙏 

Pluss at når vi går over til React 19 vil vi måtte fjerne alle disse uansett, så da blir det bare mer jobb til da 🙃 🙈

2025-02-20 14:30 UTC, cammiida commented on src/utils/party.ts
> +export function renderPartyName(party?: IParty, userParty?: IParty) {
Ooh, så party er den du har valgt å representere? `selectedParty` kanskje? 🤷‍♀️ 😅

2025-02-20 14:30 UTC, cammiida commented on src/features/language/LanguageProvider.tsx
> +export const SetShouldFetchAppLanguages = () => {
Se kommentar under 😄

2025-02-20 16:03 UTC, bjosttveit commented on src/features/language/LanguageProvider.tsx
> +  const params = new URLSearchParams(window.location.hash.split('?')[1]);
Kanskje man kunne gjort noe sånt ja, vet du om det ville vært problematisk @olemartinorg ?

2025-02-20 16:13 UTC, bjosttveit commented on src/features/language/LanguageProvider.tsx
> +  const [shouldFetchAppLanguages, setShouldFetchAppLanguages] = useState<Loading<boolean>>(IsLoading);
Det hjelper ikke å gjøre de lax så lenge den brukes i LanguageProvider og den ligger "over" de andre providerene den er avhegig av. De kommer bare alltid til å returnere ContextNotProvided istedenfor å throwe. Eneste måten å unngå noe sånt er å flytte LanguageProvider "lenger ned" så den har tilgang, men er usikker på om vi kan det siden LanguageProvider trengs nok relativt tidlig

2025-02-21 14:45 UTC, bjosttveit commented on src/core/contexts/processingContext.tsx
Jeg brukte en del tid på å prøve å erstatte alt av `useIsProcessing` med `useMutation` istedenfor, men jeg ble ikke så veldig fornøyd med hvordan koden ble til slutt, og i tillegg, ble ikke oppførselen like god (litt mer flikkering fra state-oppdateringer). Så jeg gikk heller andre veien og forbedret `ProcessingContext` og bruker den over alt istedenfor

2025-02-21 14:48 UTC, bjosttveit commented on src/features/language/LanguageProvider.tsx
> +  const params = new URLSearchParams(window.location.hash.split('?')[1]);
Jeg lar det bare være sånn foreløpig, det gir akkurat samme oppførsel som i dag, men jeg la inn en kommentar på det i tilfelle man lurer på hvorfor det ikke funker å endre `?lang` etter innlasting

2025-02-21 14:53 UTC, bjosttveit commented on src/features/language/LanguageProvider.tsx
> +  const [shouldFetchAppLanguages, setShouldFetchAppLanguages] = useState<Loading<boolean>>(IsLoading);
Jeg lar det være sånn foreløpig så jeg ikke må stokke om på alle contextene kun pga. denne bakoverkompat-tingen. Den er heldigvis ganske lett å røske ut når vi ikke trenger den lenger, og det følger tross alt samme mønster som profil-data som vi har hatt sånn lenge, bare at det er mye mer lesbart nå enn det var

2025-02-21 15:18 UTC, bjosttveit commented on test/e2e/support/custom.ts
> +      cy.findByTestId('page-navigation-trigger').click();
Jeg ryddet opp litt og byttet ut alle `findByTestId` med `findByRole`, men ellers lot jeg ting være omtrent som det er. Det er jo veldig praktiske utility commands å ha for å skrive e2e tester mot apper som bruker navigasjon

2025-02-24 13:22 UTC, bjosttveit commented
/publish

2025-02-25 11:24 UTC, bjosttveit commented
/publish

2025-02-26 12:43 UTC, merged