Cleaning up some warnings from tests and React runtime
Altinn/app-frontend-react pull request #337
Opened 2022-07-13 12:35 UTC by olemartinorg

## Description
This silences some knows warnings in unit tests, and tests for them instead of outputting them to the console. In addition, it cleans up some warnings shown in the console when running some apps.

## Verification
- [x] **Your** code builds clean without any errors or warnings
- [x] Manual testing done (required)
- [x] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [x] All tests run green

## Documentation
- ~~[ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)~~

2022-07-13 12:58 UTC, haakemon commented on src/altinn-app-frontend/src/components/base/ParagraphComponent.tsx
> +
I think this deserves a unit test 🙂

2022-07-13 19:07 UTC, haakemon requested changes

2022-07-14 07:52 UTC, olemartinorg commented on src/altinn-app-frontend/src/components/base/ParagraphComponent.test.tsx
> +    expect(shallowParagraphComponent).toMatchSnapshot();
You shouldn't be sorry! I'm a complete newbie when it comes to snapshot testing, so I hadn't considered problems like these. I fully agree.

Yep, there's potentially lots of things that shouldn't be inside a `<p>`, but I think headers were the most common case here. Either this evolves into a huge complexity, or we should just use `<div>` by default when the text is a react element. What do you think?

2022-07-14 08:50 UTC, haakemon commented on src/altinn-app-frontend/src/components/base/ParagraphComponent.test.tsx
> +    expect(shallowParagraphComponent).toMatchSnapshot();
Thanks for updating it, looks much better now 😁
I think fixing the immediate problem (checking for headers) is enough for now. There are so many cases to handle that I'm not really sure the approach where Paragraph component accepts any content as children is the best. It should probably only accept a string. But changing that would be breaking, so not something we can do easily - but at least something we need to consider for the next major version.

2022-07-14 08:51 UTC, haakemon approved these changes
🥇

2022-07-14 09:00 UTC, merged